config/routes.rb
Rails.application.routes.draw do

  get 'all_wares',   to: 'wares_lists#all_wares'
  get 'picks',       to: 'wares_lists#picks'
  get 'groups',      to: 'wares_lists#groups'
  get 'waits',       to: 'wares_lists#waits'
  get 'references',  to: 'wares_lists#references'
  resources :wares

#  get 'password_resets/new'
#  get 'password_resets/edit'
  root   'static_pages#home'
  
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contacts',  to: 'static_pages#contacts'
  get '/links',     to: 'static_pages#links'
  get '/sitemap',   to: 'static_pages#sitemap'
  get '/staff',     to: 'static_pages#staff'

  get 'sessions/new'

  get  '/signup',   to: 'users#new'
#  post '/signup',   to: 'users#create'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]

end

app/models/ware.rb
class Ware < ApplicationRecord
end

app/controllers/wares_controller.rb
class WaresController < ApplicationController
  before_action :set_ware, only: [:show, :edit, :update, :destroy]

  # GET /wares
  # GET /wares.json
  def index
    @wares = Ware.all
  end

  # GET /wares/1
  # GET /wares/1.json
  def show
  end

  # GET /wares/new
  def new
    @ware = Ware.new
  end

  # GET /wares/1/edit
  def edit
  end

  # POST /wares
  # POST /wares.json
  def create
    @ware = Ware.new(ware_params)

    respond_to do |format|
      if @ware.save
        format.html { redirect_to @ware, notice: 'Ware was successfully created.' }
        format.json { render :show, status: :created, location: @ware }
      else
        format.html { render :new }
        format.json { render json: @ware.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wares/1
  # PATCH/PUT /wares/1.json
  def update
    respond_to do |format|
      if @ware.update(ware_params)
        format.html { redirect_to @ware, notice: 'Ware was successfully updated.' }
        format.json { render :show, status: :ok, location: @ware }
      else
        format.html { render :edit }
        format.json { render json: @ware.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wares/1
  # DELETE /wares/1.json
  def destroy
    @ware.destroy
    respond_to do |format|
      format.html { redirect_to wares_url, notice: 'Ware was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ware
      @ware = Ware.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ware_params
      params.require(:ware).permit(:title, :category, :phase, :brand, :image, :details, :annex, :quantity, :q_unit, :evaluation, :in_showroom, :s_location, :weight_kg, :dim_a_cm, :dim_b_cm, :dim_h_cm, :d_location, :price, :down_p, :deadline, :contract, :bill, :conclusion, :target_no, :ok_no)
    end
end

app/helpers/wares_helper.rb
module WaresHelper
end

app/views/wares/_form.html.erb
<%= form_with(model: ware, local: true) do |form| %>
  <% if ware.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ware.errors.count, "error") %> prohibited this ware from being saved:</h2>

      <ul>
      <% ware.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, :style => "width:150px;" %>
    <%= form.label :phase %>
    <%= form.select :phase, (["Pick", "Group", "Wait", "Reference"]) %>
    <%= form.label :category %>
    <%= form.select :category, (["BabyKidToy", "ClothingShoeJewelry", "GroceryBeautyHealth", 
      "ComputerPhoneElectronics","HomeGardenTool", "HobbySportOutdoor", " CarBikeBoat", 
      " BookCollectionSouvenir", "Other"]) %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
    <%= form.label :image %>
    <%= form.text_field :image, :style => "width:150px;" %>
    <%= form.label :annex %>
    <%= form.text_field :annex %>
  </div>

  <div class="field">
    <%= form.label :evaluation %>
    <%= form.text_field :evaluation, :style => "width:30px;" %>
    <%= form.label :in_showroom, :style => "margin-left: 1em;" %>
    <%= form.check_box :in_showroom %>
    <%= form.label :deadline, :style => "margin-left: 1em;"  %>
    <%= form.date_select :deadline %>
  </div>

  <div class="field">
    <%= form.label :details %> <br />
    <%= form.text_area :details, rows: 15, cols: 75 %>
  </div>

  <div class="field">
    <%= form.label :quantity%>
    <%= form.number_field :quantity, :style => "width:50px;"  %>
    <%= form.label :quantity_unit %>
    <%= form.select :q_unit, (["piece", "kilogram", "gram", "liter", "mililiter"]) %>
    <%= form.label :target_no %>
    <%= form.number_field :target_no, :style => "width:50px;" %>
    <%= form.label :ok_no %>
    <%= form.number_field :ok_no, :style => "width:50px;" %>
  </div>

  <div class="field">
    <%= form.label :source_location %>
    <%= form.text_field :s_location %>
    <%= form.label :destination_location %>
    <%= form.select :d_location, (["atHome", "ateG4BB", "atDeliverer", "atDuty", "atSource"]) %>
  </div>

  <div class="field">
    <%= form.label :weight_kg %>
    <%= form.text_field :weight_kg, :style => "width:50px;" %>
    <%= form.label :length_cm %>
    <%= form.number_field :dim_a_cm, :style => "width:50px;" %>
    <%= form.label :width_cm %>
    <%= form.number_field :dim_b_cm, :style => "width:50px;" %>
    <%= form.label :height_cm %>
    <%= form.number_field :dim_h_cm, :style => "width:50px;" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, :style => "width:50px;" %>
    <%= form.label :down_p %>
    <%= form.text_field :down_p, :style => "width:50px;"  %>
    <%= form.label :contract %>
    <%= form.text_field :contract, :style => "width:150px;" %>
  </div>

  <div class="field">
    <%= form.label :bill %><br />
    <%= form.text_area :bill, rows: 15, cols: 50 %>
  </div>

  <div class="field">
    <%= form.label :conclusion %><br />
    <%= form.text_area :conclusion, rows: 10, cols: 50 %>
  </div>
<br />
  <div class="actions">
    <%= form.submit %>
  </div>
<br />
<% end %>

app/views/wares/edit.html.erb
<% provide(:title, "Edit Ware") %>
<div class="container-fluid" id="main">
  <h1>Editing Ware No. <%= @ware.id %></h1>
<div class="row">
  <%= render 'form', ware: @ware %>
</div>  <!-- row -->
<div class="row">
  <%= link_to 'Show Ware', @ware, type: "button", 
    class: "btn btn-info btn-sm", style: "margin-left: 5px; padding: 1px 2px;" %>
  <%= link_to 'Wares List', wares_path, type: "button",
    class: "btn btn-info btn-sm", style: "margin-left: 5px; padding: 1px 2px;" %>
</div>  <!-- row -->
  <br />
</div> <!-- container-fluid -->

app/views/wares/index.html.erb
<% provide(:title, "Wares List") %>
<div class="container-fluid" id="main">
  <h1>Wares</h1>
<div class="row">
  <p id="notice"><%= notice %></p>
  <%= link_to 'New Ware', new_ware_path,  type: "button",
    class: "btn btn-info btn-sm", style: "margin-left: 5px; padding: 1px 2px;" %>
</div>  <!-- row -->
  <br />
<div class="row">
  <div class="table-responsive">
    <table class="table table-bordered table-responsive">
      <thead>
        <tr>
          <th>Ware No</th>
          <th>Title</th>
          <th>Category</th>
          <th>Phase</th>
          <th>Brand</th>
          <th>Image</th>
    <!--      <th>Details</th> -->
          <th>Annex</th>
          <th>Quantity</th>
          <th>Quantity unit</th>
          <th>Evaluation</th>
          <th>In showroom</th>
          <th>Source location</th>
          <th>Weight kg</th>
          <th>Length cm</th>
          <th>Width cm</th>
          <th>Height cm</th>
          <th>Destination location</th>
          <th>Price</th>
          <th>Down payment</th>
          <th>Deadline</th>
          <th>Contract</th>
    <!--      <th>Bill</th> -->
    <!--      <th>Conclusion</th> -->
          <th>Target no</th>
          <th>Ok no</th>
          <th>Ware No</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @wares.each do |ware| %>
          <tr>
            <td><%= ware.id %></td>
            <td><%= ware.title %></td>
            <td><%= ware.category %></td>
            <td><%= ware.phase %></td>
            <td><%= ware.brand %></td>
            <td><%= ware.image %></td>
    <!--        <td><%#= ware.details %></td> -->
            <td><%= ware.annex %></td>
            <td><%= ware.quantity %></td>
            <td><%= ware.q_unit %></td>
            <td><%= ware.evaluation %></td>
            <td><%= ware.in_showroom %></td>
            <td><%= ware.s_location %></td>
            <td><%= ware.weight_kg %></td>
            <td><%= ware.dim_a_cm %></td>
            <td><%= ware.dim_b_cm %></td>
            <td><%= ware.dim_h_cm %></td>
            <td><%= ware.d_location %></td>
            <td><%= ware.price %></td>
            <td><%= ware.down_p %></td>
            <td><%= ware.deadline %></td>
            <td><%= ware.contract %></td>
    <!--        <td><%#= ware.bill %></td> -->
    <!--        <td><%#= ware.conclusion %></td> -->
            <td><%= ware.target_no %></td>
            <td><%= ware.ok_no %></td>
            <td><%= ware.id %></td>
            <td><%= link_to 'Show', ware %></td>
            <td><%= link_to 'Edit', edit_ware_path(ware) %></td>
            <td><%= link_to 'Destroy', ware, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- class="table-responsive" --> 

</div>  <!-- row -->
<div class="row">
  <%= link_to 'New Ware', new_ware_path,  type: "button",
    class: "btn btn-info btn-sm", style: "margin-left: 5px; padding: 1px 2px;" %>
</div> <!-- row -->
  <br />
</div> <!-- container-fluid -->

app/views/wares/new.html.erb
<% provide(:title, "New Ware") %>
<div class="container-fluid" id="main">
  <h1>New Ware</h1>
<div class="row">
  <%= render 'form', ware: @ware %>
</div>  <!-- row -->
<div class="row">
  <%= link_to 'Wares List', wares_path, type: "button",
    class: "btn btn-info btn-sm", style: "margin-left: 5px; padding: 1px 2px;" %>
</div>  <!-- row -->
  <br />
</div> <!-- container-fluid -->

app/views/wares/show.html.erb
<% provide(:title, "Show Ware") %>
<div class="container-fluid" id="main">

  <h2>Show Ware No. <%= @ware.id %></h2>

<div class="row">

  <div class="wrapper-show">

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ware.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @ware.category %>
</p>

<p>
  <strong>Phase:</strong>
  <%= @ware.phase %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @ware.brand %>
</p>

<p>
  <strong>Image:</strong>
  <%= @ware.image %>
</p>

<p>
  <strong>Details:</strong>
  <%= @ware.details %>
</p>

<p>
  <strong>Annex:</strong>
  <%= @ware.annex %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @ware.quantity %>
</p>

<p>
  <strong>Quantity unit:</strong>
  <%= @ware.q_unit %>
</p>

<p>
  <strong>Evaluation:</strong>
  <%= @ware.evaluation %>
</p>

<p>
  <strong>In showroom:</strong>
  <%= @ware.in_showroom %>
</p>

<p>
  <strong>Source location:</strong>
  <%= @ware.s_location %>
</p>

<p>
  <strong>Weight kg:</strong>
  <%= @ware.weight_kg %>
</p>

<p>
  <strong>Length cm:</strong>
  <%= @ware.dim_a_cm %>
</p>

<p>
  <strong>Width cm:</strong>
  <%= @ware.dim_b_cm %>
</p>

<p>
  <strong>Height cm:</strong>
  <%= @ware.dim_h_cm %>
</p>

<p>
  <strong>Destination location:</strong>
  <%= @ware.d_location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ware.price %>
</p>

<p>
  <strong>Down payment:</strong>
  <%= @ware.down_p %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @ware.deadline %>
</p>

<p>
  <strong>Contract:</strong>
  <%= @ware.contract %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @ware.bill %>
</p>

<p>
  <strong>Conclusion:</strong>
  <%= @ware.conclusion %>
</p>

<p>
  <strong>Target no:</strong>
  <%= @ware.target_no %>
</p>

<p>
  <strong>Ok no:</strong>
  <%= @ware.ok_no %>
</p>

  <div>
    <%= link_to 'Edit Ware', edit_ware_path(@ware), type: "button", 
      class: "btn btn-info btn-sm", style: "margin-left: 5px; padding: 1px 2px;" %>
    <%= link_to 'Wares List', wares_path, type: "button",
      class: "btn btn-info btn-sm", style: "margin-left: 5px; padding: 1px 2px;" %>
  </div>

<br>

  </div>  <!-- row -->
</div> <!-- container-fluid -->