config/routes.rb
Rails.application.routes.draw do

  get 'all_wares',   to: 'wares_lists#all_wares'
  get 'picks',       to: 'wares_lists#picks'
  get 'groups',      to: 'wares_lists#groups'
  get 'waits',       to: 'wares_lists#waits'
  get 'references',  to: 'wares_lists#references'
  resources :wares

#  get 'password_resets/new'
#  get 'password_resets/edit'
  root   'static_pages#home'
  
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contacts',  to: 'static_pages#contacts'
  get '/links',     to: 'static_pages#links'
  get '/sitemap',   to: 'static_pages#sitemap'
  get '/staff',     to: 'static_pages#staff'

  get 'sessions/new'

  get  '/signup',   to: 'users#new'
#  post '/signup',   to: 'users#create'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-sm navbar-light">
  <button class="navbar-toggler" role="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" 
    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="fa fa-bars"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to "<i class='fa fa-home'></i>".html_safe, root_path, class: "nav-link btn btn-sm", 
        title: "Go to Homepage" %></li class="nav-item">
      <li class="nav-item"><%= link_to "<i class='fa fa-phone'></i>".html_safe, contacts_path, class: "nav-link btn btn-sm", 
        title: "Contacts" %></li class="nav-item">
      <li class="nav-item"><%= link_to "<i class='fa fa-info'></i>".html_safe, about_path, class: "nav-link btn btn-sm",
        title: "About" %> </li class="nav-item">
      <li class="nav-item"><%= link_to "Help", help_path, class: "nav-link btn btn-sm" %></li class="nav-item">
      <li class="nav-item"><%= link_to "<i class='fa fa-sitemap'></i>".html_safe, sitemap_path, class: "nav-link btn btn-sm",
        title: "Sitemap" %></li class="nav-item">
      <li class="nav-item"><%= link_to "<i class='fa fa-bullseye'></i>".html_safe, staff_path, class: "nav-link btn btn-sm", 
        title: "Staff" %></li class="nav-item">
      <li class="nav-item"><%= link_to "<i class='fa fa-link'></i>".html_safe, links_path, class: "nav-link btn btn-sm", 
        title: "Links" %></li class="nav-item">
    </ul>
  </div>

  <div class="navbar-brand" style="margin-right: 0px;">
    <%= link_to "eG4 Best Buy", root_path, title: "Go to Homepage" %>
  </div>
</nav>

  <p style="text-align: center; color:  #c5b358;">Ivan Dolac, 2018</p>  

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light">

  <div class="navbar-brand">
    <%= link_to "eG4 Best Buy", root_path, title: "Go to Homepage" %>
  </div>

  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarColapse1" 
    class: "btn btn-sm" aria-controls="navbarColapse1" aria-expanded="false" 
    aria-label="Toggle navigation"> <span class="fa fa-bars"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColapse1">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "Pick", picks_path, class: "nav-link btn btn-sm", 
        title: "Vote for the Ware Purchase" %></li>
      <li class="nav-item"><%= link_to "Group", groups_path, class: "nav-link btn btn-sm", 
        title: "Join to the Buyers Group of the Ware"  %></li>
      <li class="nav-item"><%= link_to "<i class='fa fa-share-square'></i>".html_safe, waits_path, class: "nav-link btn btn-sm", 
        title: "Where is the Buyed Wares" %></li>
      <li class="nav-item"><%= link_to "<i class='fa fa-check-square'></i>".html_safe, references_path, class: "nav-link btn btn-sm", 
        title: "Reference List of Purchased Wares" %></li>
<!--      <li class="nav-item dropdown">
        <%#= link_to "<i class='fa fa-envelope'></i>".html_safe, "#", id: "navbarDropdown", 
          "data-toggle": "dropdown", class: "dropdown-toggle nav-link btn btn-sm", 
          "aria-haspopup": "true", "aria-expanded": "false", style: "margin-right: 0px",  
          title: "Received Posts" %>
        <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%#= link_to "All Posts", "#", class: "dropdown-item" %></li>
          <li><%#= link_to "News", "#", class: "dropdown-item", title: "News in eCommerce" %></li>
          <li><%#= link_to "Wares", "#", class: "dropdown-item", title: "Trending Wares on eMarket" %></li>
          <li><%#= link_to "Comments", "#", class: "dropdown-item", title: "Suggestions, Experiences, Complaints and Ware Returns" %></li>
          <li><%#= link_to "Meetings", "#", class: "dropdown-item" %></li>
          <li><%#= link_to "Q and A", "#", class: "dropdown-item" %></li>
          <li><%#= link_to "Tips", "#", class: "dropdown-item" %></li>
        </ul>
      </li> <!-- dropdown  -->
    </ul>

    <ul class="navbar-nav  my-2 my-sm-0">
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to "Account", "#", id: "navbarDropdown", 
              "data-toggle": "dropdown", class: "dropdown-toggle nav-link btn btn-sm", 
              "aria-haspopup": "true", "aria-expanded": "false", style: "margin-right: 7px" %>
            <ul class="dropdown-menu">
              <li><%= link_to "Action",root_path, class: "dropdown-item" %></li>
              <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link btn btn-sm" %></li>
        <% end %>
    </ul>

    <ul class="navbar-nav  my-2 my-sm-0">
      <li class="nav-item"><%= link_to "Members", users_path, class: "nav-link btn btn-sm", title: "All Members" %></li>
<!--      <li class="nav-item dropdown">
        <%#= link_to "Members", "#", id: "navbarDropdown", 
          "data-toggle": "dropdown", class: "dropdown-toggle nav-link btn btn-sm", 
          "aria-haspopup": "true", "aria-expanded": "false", style: "margin-right: 7px" %>
        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <li><%#= link_to "All Members", users_path, class: "dropdown-item" %></li>
          <li><%#= link_to "Buyers", "#", class: "dropdown-item" %></li>
          <li><%#= link_to "Sellers", "#", class: "dropdown-item" %></li>
          <li><%#= link_to "Investors", "#", class: "dropdown-item" %></li>
          <li><%#= link_to "Entrepreneuers", "#", class: "dropdown-item" %></li>
          <li><%#= link_to "Experts", "#", class: "dropdown-item" %></li>
        </ul>
      </li> <!-- dropdown  -->      
      <li class="nav-item"><%= link_to "<i class='fa fa-phone'></i>".html_safe, contacts_path, class: "nav-link btn btn-sm", 
        title: "Contact" %></li>
      <li class="nav-item dropdown">
        <%= link_to "Go to", "#", id: "navbarDropdown", 
          "data-toggle": "dropdown", class: "dropdown-toggle nav-link btn btn-sm", 
          "aria-haspopup": "true", "aria-expanded": "false", style: "margin-right: 0px" %>
        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <li><%= link_to "Home", root_path, class: "dropdown-item"  %></li>
          <li><%= link_to "Contact", contacts_path, class: "dropdown-item"  %></li>
          <li><%= link_to "About", about_path, class: "dropdown-item"  %></li>
          <li><%= link_to "Help", help_path, class: "dropdown-item"  %></li>
          <li><%= link_to "Sitemap", sitemap_path, class: "dropdown-item" %></li>
          <li><%= link_to "Staff", staff_path, class: "dropdown-item" %></li>
          <li><%= link_to "Links", links_path, class: "dropdown-item" %></li>
        </ul>
      </li> <!-- dropdown  -->      
    </ul>

  </div> <!-- navbar-collapse -->

</nav>  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta name="description" content="Get the best price by buying in group. 
    Members (buyers, sellers) select wares, grouping, buying, delivery. 
    GtBB include: news, experiences, Q&A, comments.">
  <meta name="keywords" content="group, best price, sell, buy, delivery">
  <meta name="author" content="Zvonimir Kolumbic">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>
<body>

  <%= render 'layouts/header' %>

  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>

  <%= debug(params) if Rails.env.development? %>

</body>
</html>